# This is the configuration file for JAZZY
# It is used to generate documentation for the project
# Find more about jazzy on https://github.com/realm/jazzy
# To generate documentation please run `fastlane documentation`

module: UBFoundation
author: Ubique
author_url: http://ubique.ch
copyright: '© 2019 [Ubique](http://ubique.ch)'

theme: fullwidth

# Make sure we clean the repository
clean: true

# Document everything marked as public
min_acl: public

# NB: The new build system doesn't support dry run yet (17 Mar 2019) -> Commenting out
# Try to optimize the run time
# xcodebuild_arguments:
  # - '-dry-run'

readme: "README.md"

# Add more documentation
documentation:
  - "CHANGELOG.md"
  - "documentation/CodeReviewProcess.md"
  - "documentation/Globals.md"
  - "fastlane/README.md"
  - "LICENSE.md"

# Exclude some files
exclude:
  - "*/UBFoundation.h" # No need to document this
  - "*/Globals/*"

# Output of the documentation
output: ./Documentation/html
