# This is the configuration file for JAZZY
# It is used to generate documentation for the project
# Find more about jazzy on https://github.com/realm/jazzy
# To generate documentation please run `fastlane documentation`

author: Ubique
author_url: http://www.ubique.ch
copyright: '© 2019 [Ubique Innovation AG](http://www.ubique.ch)'

theme: fullwidth

# Make sure we clean the repository
clean: true

# Document everything marked as public
min_acl: public

# NB: The new build system doesn't support dry run yet (17 Mar 2019) -> Commenting out
# Try to optimize the run time
# xcodebuild_arguments:
  # - '-dry-run'

readme: "README.md"

swift_build_tool: "xcodebuild"
build_tool_arguments: 
  - -scheme
  - UBKit-Package
  - -sdk
  - iphoneos

# Add more documentation
documentation:
  - "Documentation/Contribution Guide.md"
  - "Documentation/CodeReviewProcess.md"
  - "Documentation/Usage.md"
  - "CHANGELOG.md"
  - "LICENSE.md"
  - "fastlane/README.md"

