default_platform(:ios)

platform :ios do
  desc "Run the unit tests."
  lane :tests do
    scan(
        package_path: ".",
        scheme: "UBKit-Package",
        destination: "platform=iOS Simulator,name=iPhone 15 Pro 17.5,OS=17.5",
        output_directory: "./build/",
        output_types: "junit"
      )
  end
end