default_platform(:ios)

platform :ios do
  desc "Run the unit tests."
  lane :tests do
    scan(
        package_path: ".",
        scheme: "UBKit-Package",
        destination: "platform=iOS Simulator,name=iPhone 16 Pro",
        output_directory: "./build/",
        derived_data_path: "./build/",
        result_bundle: "true"
      )
  end
end