name: Run SwiftFormat
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  swiftformat:
    name: swift-format
    runs-on: ["self-hosted", "macOS"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run swift-format
        run: swift format --in-place --parallel --recursive .
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[Generated] SwiftFormat"
          add-paths: |
            *.swift
          branch: "generated/swiftformat"
          delete-branch: true
          title: "[Generated] swift-format"
          body: "This action automatically runs [swift-format](https://github.com/swiftlang/swift-format) on the project. Check the changes and merge them!"
